version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh entrypoint.sh
    restart: unless-stopped
    ports:
      - $SERVER_PORT:5000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      REDIS_HOST: redis
      REDIS_PASSWORD: $REDIS_PASSWORD
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    command: redis-server --requirepass $REDIS_PASSWORD

volumes:
  postgres:
